# ===============================================================
# COMPANY APP DEPLOY SCRIPT (Windows PowerShell)
#
# USE:
#   cd C:\Users\Rahul\Fcoy
#   powershell -ExecutionPolicy Bypass -File deploy\Deploy-Company.ps1 -Code bcoy
#
# Kya karta hai:
#   1. deploy\companies.json se <Code> company ki Firebase keys uthata hai
#   2. .env banata hai (us company ka project)  - ORIGINAL .env ka backup: .env.master.bak
#   3. npm install (agar zaroori) + npm run build
#   4. firebase deploy --only hosting,firestore:rules --project <pid>
#   5. .env wapas master pe restore
#
# Pehli baar: firebase login (ek hi baar chahiye)
# ===============================================================
param(
  [Parameter(Mandatory=$true)][string]$Code
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

Write-Host ""
Write-Host "================  COMPANY APP DEPLOY: $Code  ================" -ForegroundColor Cyan

# -- 1. Registry padho --
$registry = Get-Content "deploy\companies.json" -Raw | ConvertFrom-Json
$company = $registry.$Code
if (-not $company) {
  $names = $registry.PSObject.Properties.Name -join ', '
  throw "[X] companies.json me '$Code' nahi mila. Available: $names"
}
if ($company.alreadyDeployed -eq $true) {
  throw "[X] '$Code' = MASTER APP - ise is script se deploy mat karo (build + firebase deploy manually hota hai)."
}

foreach ($k in 'projectId','apiKey','authDomain','storageBucket','messagingSenderId','appId') {
  if ([string]::IsNullOrWhiteSpace("$($company.$k)")) {
    throw "[X] companies.json -> $Code -> '$k' KHALI hai. Pehle New-CompanyApp.ps1 chalao (auto bhar dega), ya Firebase Console se keys paste karo."
  }
}
$projId = $company.projectId.Trim()
Write-Host "Company : $($company.name)"
Write-Host "Project : $projId"
Write-Host "URL     : https://$projId.web.app/first-run  (deploy ke baad WIZARD yahan chalega)"
Write-Host ""

# -- 2. Master .env ka backup + company ka .env likho --
$envPath = ".env"
$backupPath = ".env.master.bak"
if (Test-Path $envPath) {
  Copy-Item $envPath $backupPath -Force
  Write-Host "[OK] Master .env ka backup: $backupPath" -ForegroundColor DarkGray
}

$envContent = @"
# AUTO-GENERATED by deploy/Deploy-Company.ps1 for '$Code' - $($company.name)
VITE_FIREBASE_API_KEY=$($company.apiKey.Trim())
VITE_FIREBASE_AUTH_DOMAIN=$($company.authDomain.Trim())
VITE_FIREBASE_PROJECT_ID=$($company.projectId.Trim())
VITE_FIREBASE_STORAGE_BUCKET=$($company.storageBucket.Trim())
VITE_FIREBASE_MESSAGING_SENDER_ID=$($company.messagingSenderId.Trim())
VITE_FIREBASE_APP_ID=$($company.appId.Trim())
"@
Set-Content -Path $envPath -Value $envContent -Encoding ascii
Write-Host "[OK] .env ($Code ke Firebase keys se) likh diya" -ForegroundColor Green

try {
  # -- 3. Build --
  if (-not (Test-Path "node_modules")) {
    Write-Host ">> npm install..." -ForegroundColor Yellow
    npm install --no-audit --no-fund
    if ($LASTEXITCODE -ne 0) { throw "npm install fail ho gaya" }
  }
  Write-Host ">> npm run build..." -ForegroundColor Yellow
  npm run build
  if ($LASTEXITCODE -ne 0) { throw "Build fail ho gaya - upar error dekho" }

  # -- 4. Deploy --
  Write-Host ">> firebase deploy ($projId)..." -ForegroundColor Yellow
  firebase deploy --only hosting,firestore:rules --project $projId
  if ($LASTEXITCODE -ne 0) { throw "firebase deploy fail - 'firebase login' chala hai na? Project me Hosting/Firestore enabled hai?" }

  Write-Host ""
  Write-Host "================  DEPLOY COMPLETE: $($company.name)  ================" -ForegroundColor Green
  Write-Host ""
  Write-Host "AGLE 3 STEPS (abhi karo):" -ForegroundColor Cyan
  Write-Host "  1. Kholo:  https://$projId.web.app/first-run"
  Write-Host "  2. Wizard bharo -> pehla CC account + letterhead + plan banega"
  Write-Host "  3. Master app ke Owner Panel me is customer ko SUBSCRIPTION assign karo (billing ledger)"
  Write-Host ""
}
finally {
  # -- 5. .env wapas master pe --
  if (Test-Path $backupPath) {
    Move-Item $backupPath $envPath -Force
    Write-Host "[OK] .env wapas master pe restore ho gaya" -ForegroundColor DarkGray
  }
}
